language: c
before_script:
- wget http://ftp.gnu.org/gnu/make/make-4.2.1.tar.gz
- tar -xf make-4.2.1.tar.gz
- cd make-4.2.1
- ./configure --prefix=/usr
- sudo make install
- cd ..
- sudo apt-get install imagemagick
- git submodule init
- git submodule update
script: make test
sudo: required
